services:

  postgres:
    image: postgres:15
    container_name: spoting-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwordfuyyo321
      POSTGRES_DB: spoting
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: spoting-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
