from .openssl import OPENSSL_API_RULES
from .mbedtls import MBEDTLS_API_RULES
from .wolfssl import WOLFSSL_API_RULES
from .gnutls import GNUTLS_API_RULES
from .nss import NSS_API_RULES
from .libsodium import LIBSODIUM_API_RULES
from .botan import BOTAN_API_RULES
from .libgcrypt import LIBGCRYPT_API_RULES

CRYPTO_API_RULES = {}

CRYPTO_API_RULES.update(OPENSSL_API_RULES)
CRYPTO_API_RULES.update(MBEDTLS_API_RULES)
CRYPTO_API_RULES.update(WOLFSSL_API_RULES)
CRYPTO_API_RULES.update(GNUTLS_API_RULES)
CRYPTO_API_RULES.update(NSS_API_RULES)
CRYPTO_API_RULES.update(LIBSODIUM_API_RULES)
CRYPTO_API_RULES.update(BOTAN_API_RULES)
CRYPTO_API_RULES.update(LIBGCRYPT_API_RULES)