"""add x_profil_tugasan_ejen

Revision ID: 09f9253058bc
Revises: 061d373a1287
Create Date: 2026-08-05 14:53:40.705147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09f9253058bc'
down_revision: Union[str, Sequence[str], None] = '061d373a1287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('x_profil_tugasan_ejen',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profil_tugasan_id', sa.BigInteger(), nullable=False),
    sa.Column('ejen_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='Pending', nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ejen_id'], ['ejen.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profil_tugasan_id'], ['x_profil_tugasan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profil_tugasan_id', 'ejen_id', name='uq_task_agent')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('x_profil_tugasan_ejen')
    # ### end Alembic commands ###
