"""initial tables

Revision ID: a961b45f67b5
Revises: 
Create Date: 2026-03-18 12:55:08.323432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a961b45f67b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pelanggan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod', sa.String(length=50), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('cipta_pada', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('kemaskini_pada', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod')
    )
    op.create_index(op.f('ix_pelanggan_id'), 'pelanggan', ['id'], unique=False)
    op.create_table('organisasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pelanggan_id', sa.Integer(), nullable=False),
    sa.Column('kod', sa.String(length=50), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('cipta_pada', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('kemaskini_pada', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pelanggan_id'], ['pelanggan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod')
    )
    op.create_index(op.f('ix_organisasi_id'), 'organisasi', ['id'], unique=False)
    op.create_table('sub_organisasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisasi_id', sa.Integer(), nullable=False),
    sa.Column('kod', sa.String(length=50), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('cipta_pada', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('kemaskini_pada', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organisasi_id'], ['organisasi.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod')
    )
    op.create_index(op.f('ix_sub_organisasi_id'), 'sub_organisasi', ['id'], unique=False)
    op.create_table('tapak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_organisasi_id', sa.Integer(), nullable=False),
    sa.Column('kod', sa.String(length=50), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('cipta_pada', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('kemaskini_pada', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sub_organisasi_id'], ['sub_organisasi.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod')
    )
    op.create_index(op.f('ix_tapak_id'), 'tapak', ['id'], unique=False)
    op.create_table('profil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tapak_id', sa.Integer(), nullable=False),
    sa.Column('kod', sa.String(length=50), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('cipta_pada', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('kemaskini_pada', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tapak_id'], ['tapak.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod')
    )
    op.create_index(op.f('ix_profil_id'), 'profil', ['id'], unique=False)
    op.create_table('tugasan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profil_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=True),
    sa.Column('jenis', sa.String(length=100), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('ip_start', sa.String(length=45), nullable=True),
    sa.Column('ip_end', sa.String(length=45), nullable=True),
    sa.Column('cipta_pada', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profil_id'], ['profil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tugasan_id'), 'tugasan', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tugasan_id'), table_name='tugasan')
    op.drop_table('tugasan')
    op.drop_index(op.f('ix_profil_id'), table_name='profil')
    op.drop_table('profil')
    op.drop_index(op.f('ix_tapak_id'), table_name='tapak')
    op.drop_table('tapak')
    op.drop_index(op.f('ix_sub_organisasi_id'), table_name='sub_organisasi')
    op.drop_table('sub_organisasi')
    op.drop_index(op.f('ix_organisasi_id'), table_name='organisasi')
    op.drop_table('organisasi')
    op.drop_index(op.f('ix_pelanggan_id'), table_name='pelanggan')
    op.drop_table('pelanggan')
    # ### end Alembic commands ###
